### ISSUE TITLE
Theme not set on first load

### ISSUE THREAD

**Issue by Lcarv20** [nodetec/hackrnews#15]
Theme is not being set on the first time the page is loaded. This causes the app (even if the dark theme is selected) to not take effect and change according the operating system.

**Comment by masterghost2002** [comment]
can you please elaborate the issue?

**Comment by Lcarv20** [comment]
@masterghost2002, sorry for being brief.
the steps to reproduce the issue are the following:

- open your browser and load the page for the first time (I believe the port to be 3000)
- select light or dark theme
- change your OS system

this will make the page dynamically change theme as well even if you have a specific theme selected.

However if you reload the page then it works properly. So it only happens when it is first loaded. This will not affect the users experience I would say, but it's not working properly.

I also have to apologise for not specifying on the README but the branch with the latest features is dev.

**Comment by masterghost2002** [comment]
hey @Lcarv20  I just fixed the problem by making some changes on the code, after verifying the code and some refinement will push it.

**Comment by Lcarv20** [comment]
Thanks @masterghost2002, I hope you understood what I meant above because on the 3rd bullet (change your OS system) I meant "change your os system theme".

**Comment by masterghost2002** [comment]
yes @Lcarv20 I did what you said :)

**Comment by masterghost2002** [comment]
@Lcarv20 https://drive.google.com/file/d/197AK-OO2hprNkhnE39Tg_alh0Gmrb3hv/view?usp=sharing here is the expected output video clip

**Comment by Lcarv20** [comment]
Looks good! thanks. Submit when you ready!

**Comment by masterghost2002** [comment]
@Lcarv20 just open the pr can u review it
